sudo: false

language: php
php:
  - '7.0'

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"


services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - npm i -g npm
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

  # install composer dependencies
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

  # setup application
  - |
    ./init --env=Development
    sed -i s/'username' => 'yiiframeworkcom',/'username' => 'travis',/ config/params-local.php
    sed -i s/'password' => 'yiiframeworkcom',/'password' => '',/ config/params-local.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web-local.php

  # install clientside stuff
  - npm install -g gulp-cli
  - npm install -g yarn
  - yarn install

before_script:
  # show some versions and env information
  - php --version
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
  - npm --version

  # compile assets
  - gulp build

  # initialize databases
  #- |
  #  if [ $TASK_TESTS_PHP == 1 ]; then
  #    travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
  #    mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
  #    mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
  #    mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
  #  fi

script:
  - php -S localhost:8080 -t web > /dev/null 2>&1 &
  - vendor/bin/codecept run
